# Generated by Django 3.0.8 on 2020-07-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0004_auto_20200727_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
