# Generated by Django 3.0.8 on 2020-08-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20200727_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(default='none', max_length=500, null=True),
        ),
    ]
