# Generated by Django 3.1 on 2020-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20200809_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('electric', 'Electric'), ('gas', 'Gas'), ('insurance', 'Insurance'), ('grocery', 'Grocery'), ('other', 'Other'), ('bills', 'Bills'), ('auto', 'Auto')], default='Paycheck', max_length=100),
        ),
    ]
