# Generated by Django 3.1 on 2020-08-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20200810_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('electric', 'Electric'), ('gas', 'Gas'), ('insurance', 'Insurance'), ('grocery', 'Grocery'), ('other', 'Other'), ('bills', 'Bills'), ('auto', 'Auto'), ('utilities', 'Utilities'), ('credit card', 'Credit Card'), ('credit card principle', 'Credit Card Principle'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment')], default='Paycheck', max_length=100),
        ),
    ]
