//Errors and messaging
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
//User Accounts
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//Expenses
export const GET_EXPENSES = "GET_EXPENSES";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETING_EXPENSE = "DELETING_EXPENSE";
export const DELETING_EXPENSE_CANCELLED = "DELETING_EXPENSE_CANCELLED";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const EDITING_EXPENSE = "EDITING_EXPENSE";
export const UPDATING_EXPENSE = "UPDATING_EXPENSE";
export const UPDATING_EXPENSE_SUCCESS = "UPDATING_EXPENSE_SUCCESS";
export const UPDATING_EXPENSE_FAILED = "UPDATING_EXPENSE_FAILED";
export const UPDATING_EXPENSE_CANCELLED = "UPDATING_EXPENSE_CANCELLED";
export const GET_EXPENSE_CATEGORIES = "GET_EXPENSE_CATEGORIES";
//Incomes
export const GET_INCOMES = "GET_INCOMES";
export const DELETE_INCOME = "DELETE_INCOME";
export const DELETING_INCOME = "DELETING_INCOME";
export const DELETING_INCOME_CANCELLED = "DELETING_INCOME_CANCELLED";
export const ADD_INCOME = "ADD_INCOME";
export const EDITING_INCOME = "EDITING_INCOME";
export const UPDATING_INCOME = "UPDATING_INCOME";
export const UPDATING_INCOME_SUCCESS = "UPDATING_INCOME_SUCCESS";
export const UPDATING_INCOME_FAILED = "UPDATING_INCOME_FAILED";
export const UPDATING_INCOME_CANCELLED = "UPDATING_INCOME_CANCELLED";
export const GET_INCOME_CATEGORIES = "GET_INCOME_CATEGORIES";
//Graphs
export const SET_BAR_LAYOUT = "SET_BAR_LAYOUT";
export const SET_BAR_GROUPING = "SET_BAR_GROUPING";
export const SET_SUMMARY_YEAR = "SET_SUMMARY_YEAR";
export const SET_BAR_CATEGORY = "SET_BAR_CATEGORY";
