# Generated by Django 3.0.8 on 2020-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_date',
            field=models.DateTimeField(default='2016-01-01'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
