# Generated by Django 3.0.8 on 2020-08-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20200727_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(default='none', max_length=500, null=True),
        ),
    ]
